# Generated by Django 5.0.6 on 2024-06-20 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NombreAbstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='regionVitivinicola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la región vitivinícola', max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='tipoUva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de uva', max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='varietal',
            fields=[
                ('nombreabstract_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='registrarVarietal.nombreabstract')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del varietal', verbose_name='Descripción')),
                ('porcentajeComposicion', models.DecimalField(decimal_places=2, help_text='Porcentaje de composición del varietal en el vino', max_digits=5, verbose_name='Porcentaje de composición')),
                ('regionVitivinicola', models.ForeignKey(help_text='Región vitivinícola del varietal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrarVarietal.regionvitivinicola', verbose_name='Región vitivinícola')),
                ('tipoUva', models.ForeignKey(help_text='Tipo de uva del varietal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='registrarVarietal.tipouva', verbose_name='Tipo de uva')),
            ],
            bases=('registrarVarietal.nombreabstract',),
        ),
    ]
